name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: 1.14.x
            otp: 25.x

    steps:
      - uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '${{ matrix.otp }}'
          elixir-version: '${{ matrix.elixir }}'

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Compile code
        run: mix compile --warnings-as-errors

      - name: Run style and code consistency checks
        run: |
          mix format --check-formatted
          mix credo --strict

      - name: Run tests
        run: |
          epmd -daemon
          mix test --trace
